# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

random:
  url:   /random
  param: { module: citation, action: random }

citation:
  url:   /citation/:id
  param: { module: citation, action: show }

last:
  url:   /last
  param: { module: citation, action: last }

homepage:
  url:   /
  param: { module: default, action: index }