<?php

/**
 * AuthorWikipediaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthorWikipediaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AuthorWikipediaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AuthorWikipedia');
    }
}