<?php

/**
 * AuthorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AuthorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Author');
    }
    
  	public static function addAuthor($author_name) {
  		
      if (($author_name != '') && (strlen($author_name) > 0))
      {
        $authors = Doctrine::getTable('Author')->findByName($author_name);
        if (count($authors) == 0)
        {
          $Author = new Author;
          $Author->name = $author_name;
          $Author->is_active = true;
          $Author->save();
					$Author->free(true);
          return true;
        }
      }
      
      return false;
  	}
  	
    public function retrieveForSelect($q, $is_table = true, $limit = 50) {
    	
        $q = $this->createQuery('a')
            ->where('a.name LIKE ?', '%'.$q.'%')
            ->limit($limit);

        if ($is_table) {
	        $authors = array();
	
	        foreach ($q->execute() as $author) {
	            $authors[] = array (
	            		'id' => $author->getId(),
	            		'value' => $author->getName()
	            );
	        }
	
	        return $authors;
        } 
	      
        return $q->execute();
    }
  	
}