<?php

/**
 * Author
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    citations-vi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Author extends BaseAuthor
{
	public function getNbCitations() {
		return count($this->Citations);
	}
}
