<?php

/**
 * AuthorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AuthorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Author');
    }
    
  	public static function addAuthor($author_name) {
  		
      if ($author_name != '')
      {
        $authors = Doctrine::getTable('Author')->findByName($author_name);
        if (count($authors) == 0)
        {
          $Author = new Author;
          $Author->name = $author_name;
          $Author->is_active = true;
          $Author->save();
          return true;
        }
      }
      
      return false;
  	}
}