<?php

/**
 * AuthorDBPediaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthorDBPediaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AuthorDBPediaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AuthorDBPedia');
    }
}