<?php

/**
 * Author
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    citations-vi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Author extends BaseAuthor
{
	public function getNbCitations() {
		return count($this->Citations);
	}
	
	public function hasDBPedia() {
		return count($this->DBPedia) != 0;
	}
	
	public function getHasDBPedia() {
		return $this->hasDBPedia();
	}
	
	public function hasWikipedia() {
		return count($this->Wikipedia) != 0;
	}
	
	public function getHasWikipedia() {
		return $this->hasWikipedia();
	}
	
	public function getShortDescription($limit = 500) {
		if (strlen($this->getDescription()) <= $limit)
			return $this->getDescription();
		
		return substr($this->getDescription(), 0, stripos($this->getDescription(), ' ', $limit)+1 ).'...';
	}
	
	public function getDescription() {
		
		if ($this->hasDBPedia()) {
			foreach ($this->DBPedia as $dbPedia) {
				if ($dbPedia->comment != '')
					return $dbPedia->comment;
				if ($dbPedia->abstract != '')
					return $dbPedia->abstract;
			}
		}
		
		if ($this->hasWikipedia()) {
			foreach ($this->Wikipedia as $wikipedia) {
				if ($wikipedia->abstract != '')
					return $wikipedia->abstract;
			}
		}
		
		return '';
	}
}
