<?php

/**
 * Citation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    citations-vi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Citation extends BaseCitation
{
	public function addTags($tags) {
		array_unique($tags, SORT_LOCALE_STRING);
		
		if (count($tags) > 0) {
			foreach ($tags as $tag) {
				$this->addTag($tag);
			}
		}
	}
	
	public function addTag($tag) {
		$Tag = Doctrine::getTable('Tag')->findOneByName($tag);
		
		foreach ($this->Tags as $Linked_Tag) {
	    if ($Linked_Tag->id == $Tag->id) {
				return false;
			}
		}
		
		try {
			$TagCitation = new TagCitation;
			$TagCitation->tag_id = $Tag->id;
			$TagCitation->citation_id = $this->id;
			if ($TagCitation->isValid()) {
				$TagCitation->save();
				$TagCitation->free(true);
		  	return true;
			}
	  } catch (\PDOException $e) {
	  }
		
		return false;
	}
	
	public function generateSlug() {
		$slug = $this->id;
		
		foreach ($this->Tags as $Tag) {
			$slug .= '-'.$Tag->slug;
		}
		
		if (strlen($slug) == 0) {
			$slug = $this->id.'-'.$hash;
		}
		
		if (strlen($slug) == 0) {
			$slug = $this->id;
		}
		
		$this->slug = $slug;
		$this->save();
		
		return $this->slug;
	}
}
