<?php

/**
 * CitationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CitationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CitationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Citation');
    }
    
  public static function buidHash($quote, $author) {
  	$text = $quote.' '.$author;
  	
	  // replace non letter or digits by -
	  $text = preg_replace('~[^\\pL\d]+~u', ' ', $text);
	 
	  // trim
	  $text = trim($text, '-');
	 
	  // transliterate
	  if (function_exists('iconv'))
	  {
	    $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);
	  }
	 
	  // lowercase
	  $text = strtolower($text);
	 
	  // remove unwanted characters
	  $text = preg_replace('~[^-\w]+~', ' ', $text);
	  
    $text = str_replace(' ', '-', $text);
    $hash = trim($text, '-');
    
    return $hash;
  }
    
  public static function addCitation($quote) {
    
      if ($quote['quote'] != '')
      {
      	$hash = CitationTable::buidHash($quote['quote'], $quote['author']);
      	
        $citations = Doctrine::getTable('Citation')->findByHash($hash);
        if (count($citations) == 0)
        {
          $Citation = new Citation;
          $Citation->quote = trim($quote['quote']);
          
          if ((array_key_exists('author', $quote)) && ($quote['author'] != '')) {
        		$author = Doctrine::getTable('Author')->findOneByName($quote['author']);
          	$Citation->author_id = $author->id;
          }
          
          if (array_key_exists('source', $quote) && ($quote['source'] == ''))
          	$Citation->source = $quote['source'];
          
          $Citation->last_published_at  = '0000-00-00 00:00:00';
          $Citation->is_active = true;
          $Citation->hash = $hash;
          $Citation->save();
          
          
          $slug = $Citation->id;
          foreach ($quote['tags'] as $tag) {
          	$Tag = Doctrine::getTable('Tag')->findOneByName($tag);
          	
          	$slug .= '-'.$Tag->slug;
          	
          	$TagCitation = new TagCitation;
          	$TagCitation->tag_id = $Tag->id;
          	$TagCitation->citation_id = $Citation->id;
          	$TagCitation->save();
          }
          $Citation->slug = trim($slug, '-');
          $Citation->save();
          
          return true;
        } else {
        	$Citation = $citations[0];
          $Citation->note = $Citation->note + 1;
        	
          if (array_key_exists('source', $quote) && ($quote['source'] == ''))
          	$Citation->source = $quote['source'];
          
          $Citation->save();
          
	          if (count($quote['tags']) > 0) {
	          	foreach ($quote['tags'] as $tag) {
		          	$Tag = Doctrine::getTable('Tag')->findOneByName($tag);
		          	
		          	$already = false;
		          	foreach ($Citation->Tags as $Linked_Tag) {
		          		if ($Linked_Tag->id = $Tag->id) {
		          			$already = true;
		          			break;
		          		}
		          	}
			          try {
					          	if (!$already) {
						          	$TagCitation = new TagCitation;
						          	$TagCitation->tag_id = $Tag->id;
						          	$TagCitation->citation_id = $Citation->id;
						          	$TagCitation->save();
					          	}
			          } catch (Exception $e) {
			          	echo '*******************erreur**************************';
			          }
	          	}
	          }
        }
      }
		return false;
  }
}