<?php

/**
 * SendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Send');
    }
}