<?php

/**
 * SourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Source');
    }
    
  public static function retrieveLast($limit = 25) {
  	$query = Doctrine::getTable('Source')
  		->createQuery()
	    ->where('is_active = ?', 1)
	    ->limit($limit)
	    ->orderBy('updated_at DESC');
  	
  	return $query->execute();
  }
}