<?php

/**
 * Source
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    citations
 * @subpackage model
 * @author     Nathanaël Martel <nathanael@fam-martel.eu>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Source extends BaseSource
{
	
	public function getShortUrl($traker = '?pk_campaign=twitter&pk_kwd=twitter') {
		return 'http://citation-ou-proverbe.fr/s/'.$this->id.$traker;
	}
}
