<?php

/**
 * TagCitationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagCitationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagCitationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagCitation');
    }
}