<?php

/**
 * TagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tag');
    }
    
  	public static function addTag($tag) {
    
      if ($tag != '')
      {
        $tags = Doctrine::getTable('Tag')->findByName($tag);
        if (count($tags) == 0)
        {
          $Tag = new Tag;
          $Tag->name = $tag;
          $Tag->is_active = true;
          $Tag->save();
          return true;
        }
      }
      
      return false;
  	}
}