# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:

all:
  pager: 25

  medias:
    dir: /medias/citations/
    jpg_quality: 90
    
  sfImageTransformPlugin:
    mime_type:
      auto_detect: true

  sfImageTransformPlugin:
    default_adapter: GD # GD or ImageMagick
    default_image:
      mime_type: image/png
      filename: Untitled.png
      width: 100
      height: 100
      color: '#000000'
    font_dir: %SF_LIB_DIR%/fonts
    mime_type:
      auto_detect: true
      library: gd_mime_type #  gd_mime_type (GD), Fileinfo (PECL), MIME_Type (PEAR)

  Contact:
    email_subject: '[citation-ou-proverbe] Formulaire de contact'
    email_from: contact@citation-ou-proverbe.fr
    email_to: contact@citation-ou-proverbe.fr
    email_bcc: []

  Send:
    email_subject: 'Vous avez reçu une citation'
    email_from: contact@citation-ou-proverbe.fr
    email_bcc: []
  
  newsletter:
    mail_subject_newsletter: "Confirmation de votre abonnement à la citation quotidienne"
    mail_from: contact@citation-ou-proverbe.fr
    mail_to: contact@citation-ou-proverbe.fr
  
  proposition:
    email_subject: "proposition de nouvelle citation"
    email_from: contact@citation-ou-proverbe.fr
    email_to: nathanael@fam-martel.eu
    
    
    