# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:

all:
  pager: 25

  medias:
    dir: /medias/citations/
    jpg_quality: 90
    
  sfImageTransformPlugin:
    mime_type:
      auto_detect: true

  sfImageTransformPlugin:
    default_adapter: GD # GD or ImageMagick
    default_image:
      mime_type: image/png
      filename: Untitled.png
      width: 100
      height: 100
      color: '#FFFFFF'
    font_dir: %SF_LIB_DIR%/fonts
    mime_type:
      auto_detect: false
      library: gd_mime_type #  gd_mime_type (GD), Fileinfo (PECL), MIME_Type (PEAR)
      