




citation_image:
  url:   /medias/:author/:slug.:sf_format
  param: { module: media, action: show }
citation_image_short:
  url:   /i/:id
  param: { module: media, action: short }


author_short:
  url:   /a/:id
  param: { module: author, action: short }

citation_short:
  url:   /c/:id
  param: { module: citation, action: short }
  
citation:
  url:   /:author/:slug
  param: { module: citation, action: show }
  
author:
  url:   /:slug
  param: { module: author, action: show }

homepage:
  url:   /
  param: { module: default, action: index }