
# Newsletter
newsletter_desabonnement:
  url: /desabonnement/:code
  param: { module: newsletter, action: del }
  
newsletter:
  url: /abonnement
  param: { module: newsletter, action: new }
  
newsletter_confirmation:
  url: /abonnement/confirmation/:code
  param: { module: newsletter, action: confirmation }
  
newsletter_create:
  url: /abonnement/create
  param: { module: newsletter, action: create }
  
newsletter_update:
  url: /abonnement/update
  param: { module: newsletter, action: update }
  
newsletter_edit:
  url: /abonnement/edit
  param: { module: newsletter, action: edit }
  

new_citation:
  url:   /proposer-citation
  param: { module: proposition, action: index }
new_citation_validation:
  url:   /proposer-citation/validation
  param: { module: proposition, action: create }
new_citation_validation_approbation:
  url:   /proposer-citation/validation/approbation/:id
  param: { module: proposition, action: approbate }
  

contact:
  url:   /contact
  param: { module: contact, action: index }
contact_validation:
  url:   /contact/validation
  param: { module: contact, action: create }

send_mail_validation:
  url:   /envoyer/validation
  param: { module: send, action: create }
send_mail:
  url:   /envoyer/:id
  param: { module: send, action: index }


portrait_image:
  url:   /medias/:author/portrait.:authorb.:effect.:sf_format
  param: { module: media, action: portrait }
citation_image:
  url:   /medias/:author/:authorb.:slug.:sf_format
  param: { module: media, action: show }
#wallpaper_image_background:
#  url:   /wallpaper/:author.:id.:width.:height.:bgcolor.:textcolor.:authorname.:portrait.:background.:sf_format
#  param: { module: media, action: custom }
#wallpaper_image:
#  url:   /wallpaper/:author.:id.:width.:height.:bgcolor.:textcolor.:authorname.:portrait.:sf_format
#  param: { module: media, action: custom }
#wallpaper_upload:
#  url:   /wallpaper-upload
#  param: { module: media, action: upload }
citation_twitter_image:
  url:   /twitter/:author/:id.:sf_format
  param: { module: media, action: twitter }
citation_image_short:
  url:   /i/:id
  param: { module: media, action: short }

#citation_wallpaper:
#  url:   /fond-ecran/:author/:slug
#  param: { module: media, action: wallpaper }

source_short:
  url:   /s/:id
  param: { module: source, action: short }

author_short:
  url:   /a/:id
  param: { module: author, action: short }

citation_short:
  url:   /c/:id
  param: { module: citation, action: short }

tag_short:
  url:   /t/:id
  param: { module: tag, action: short }


authors_search:
  url:   /auteurs/search
  param: { module: author, action: search }
authors_search_page:
  url:   /auteurs/recherche
  param: { module: author, action: recherche }
authors:
  url:   /auteurs
  param: { module: author, action: index }
authors_page:
  url:   /auteurs/:page
  param: { module: author, action: index }

random:
  url:   /citation
  param: { module: citation, action: random }

tags:
  url:   /themes
  param: { module: tag, action: index }
tags_page:
  url:   /themes/:page
  param: { module: tag, action: index }

feed:
  url:   /feed
  param: { module: citation, action: feed }
feed-sources:
  url:   /feed-sources
  param: { module: source, action: feed }
sitemap:
  url:   /sitemap
  param: { module: citation, action: sitemap }
sitemap_page:
  url:   /sitemap/:page
  param: { module: citation, action: sitemap }
  
  
tag:
  url:   /theme/:slug
  param: { module: tag, action: show }
tag_page:
  url:   /theme/:slug/:page
  param: { module: tag, action: show }
  
source:
  url:   /oeuvre/:author/:slug
  param: { module: source, action: show }
source_page:
  url:   /oeuvre/:author/:slug/page/:page
  param: { module: source, action: show }
  
citation:
  url:   /:author/:slug
  param: { module: citation, action: show }
citation_note:
  url:   /note/citation/:id
  param: { module: citation, action: note }
  
author:
  url:   /:slug
  param: { module: author, action: show }
author_page:
  url:   /:slug/page/:page
  param: { module: author, action: show }

homepage:
  url:   /
  param: { module: home, action: index }
