




citation_image:
  url:   /medias/:author/:authorb.:slug.:sf_format
  param: { module: media, action: show }
citation_image_short:
  url:   /i/:id
  param: { module: media, action: short }


author_short:
  url:   /a/:id
  param: { module: author, action: short }

citation_short:
  url:   /c/:id
  param: { module: citation, action: short }

tag_short:
  url:   /t/:id
  param: { module: tag, action: short }
  
tag:
  url:   /theme/:slug
  param: { module: tag, action: show }
  
citation:
  url:   /:author/:slug
  param: { module: citation, action: show }
  
author:
  url:   /:slug
  param: { module: author, action: show }

homepage:
  url:   /
  param: { module: home, action: index }