generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Author
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          author
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions: ~
      fields:  ~
      list:
          display: [=name, nb_citations, slug, is_active, has_thumbnail, hasWikipedia, hasDBPedia, updated_at]
          max_per_page: 50
          sort: [updated_at, desc]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
