

Option:
  tableName: option_table
  actAs:
    Timestampable:

  columns:
    option_key:  varchar(255)
    option_value: {type: string()}

  options:
    collate: utf8_unicode_ci
    charset: utf8

Page:
  tableName: page
  actAs:
    Timestampable:

  columns:
    url: 
      type: varchar(255)
      unique: true
    website: varchar(255)
    title: varchar(255)
    nb_citations: int
    http_code: varchar(4)
    loading_time: varchar(10)
    downloaded_date: datetime
    parsed_date: datetime

  options:
    collate: utf8_unicode_ci
    charset: utf8
    

Author:
  connection: doctrine
  tableName: author
  actAs:
    Sluggable:
      unique: true
      fields: [name]
      canUpdate: true
    Timestampable:
    
  columns:
    name: {type: string(255), unique: true}
    dbpedia_at: {type: datetime, default: null}
    wikipedia_at: {type: string(255), default: null}
    has_thumbnail: {type: boolean, default: null}
    is_active: {type: boolean}
      
  options:
    collate: utf8_unicode_ci
    charset: utf8


AuthorDBPedia:
  connection: doctrine
  tableName: author_dbpedia
  actAs:
    Timestampable:
    
  columns:
    author_id: {type: integer, notnull: true}
    name: {type: string(255)}
    abstract: {type: string(), default: null}
    comment: {type: string(), default: null}
    thumbnail: {type: string(255), default: null}
    birth_date: {type: string(255), default: null}
    death_date: {type: string(255), default: null}
#    birth_place: {type: string(255), default: null}
#    death_place: {type: string(255), default: null}
    wikipedia_url: {type: string(255), default: null}
    dbpedia_url: {type: string(255), default: null}
#    occupation: {type: string(255), default: null}
#    notableworks: {type: string(255), default: null}
    
  relations:
    Author:
      class: Author
      foreignAlias: DBPedia
      local: author_id
      foreign: id
      onDelete: cascade
      
  options:
    collate: utf8_unicode_ci
    charset: utf8


AuthorWikipedia:
  connection: doctrine
  tableName: author_wikipedia
  actAs:
    Timestampable:
    
  columns:
    author_id: {type: integer, notnull: true}
    name: {type: string(255)}
    abstract: {type: string(), default: null}
    thumbnail: {type: string(255), default: null}
    wikipedia_url: {type: string(255), default: null}
    
  relations:
    Author:
      class: Author
      foreignAlias: Wikipedia
      local: author_id
      foreign: id
      onDelete: cascade
      
  options:
    collate: utf8_unicode_ci
    charset: utf8
    
Citation:
  connection: doctrine
  tableName: citation
  actAs:
    Timestampable:
  columns:
    quote: {type: string()}
    author_id: {type: integer, notnull: true}
    source: {type: string(255)}
    is_active: {type: boolean}
    last_published_at: {type: datetime}
    hash: {type: string(255), unique: true}
    note: {type: int, default: 0}
    view: {type: int, default: 0}
    slug: {type: string(255), unique: true}
    color: {type: string(255)}
    text_color: {type: string(255)}
    
  relations:
    Author:
      class: Author
      foreignAlias: Citations
      local: author_id
      foreign: id
      onDelete: cascade
      
  options:
    collate: utf8_unicode_ci
    charset: utf8
    
Tag:    
  tableName: tag
  actAs:
    Sluggable:
      unique: true
      fields: [name]
    Timestampable:

  columns:
    name: { type: string(255), notnull: true, unique: true }
    is_active: {type: boolean}
    
  relations:
    Citations:
      class: Citation
      refClass: TagCitation
      foreignAlias: Tags
      
  options:
    collate: utf8_unicode_ci
    charset: utf8
    
TagCitation:    
  tableName: tag_citation

  columns:
    tag_id: {type: integer, primary: true}
    citation_id: {type: integer, primary: true}

  options:
    collate: utf8_unicode_ci
    charset: utf8
    
    
    
    
Contact:
  tableName: contact
  actAs:
    Timestampable:

  columns:
    name: { type: string(255), notnull: true }
    email: { type: string(255), notnull: true }
    comments: clob

  options:
    collate: utf8_unicode_ci
    charset: utf8
    
    
    
    